### ISSUE TITLE
객체의 메서드에 화살표 함수 사용

### ISSUE THREAD

**Issue by BKJang** [Dae-Hwa/tetris#1]
[createBlock.js](https://github.com/Dae-Hwa/tetris/blob/master/src/createBlock.js)에서 selectBox 객체의 메서드를 정의할 때 화살표 함수를 사용하여 정의하고 있습니다.

화살표 함수는 객체의 메서드를 정의할 때 사용하면 `this`가 `window`에 바인딩되기 때문에 사용을 지양하는걸로 알고 있습니다.

```js
var lang = 'Korean';

const obj = {
    lang : 'English',
    foo : () => { 
        console.log('outerFunc : ', this.lang);
    }
}

obj.foo(); //outerFunc : Korean
```

축약 메서드 표현법을 사용하는 것을 추천드립니다.

```js
var lang = 'Korean';

const obj = {
    lang : 'English',
    foo () { 
        console.log('outerFunc : ', this.lang);
    }
}

obj.foo(); //outerFunc : English
```

[참고](https://github.com/BKJang/do-you-know-vanilla/issues/18)

**Comment by Dae-Hwa** [comment]
@BKJang 좋은 의견 감사합니다. 반영하여 수정하였습니다.
